### ISSUE TITLE
Parse error on new lines when used from CLJS (browser)

### ISSUE THREAD

**Issue by tdreyno** [superkonduktr/wet#12]
I'm loading a template file over HTTP, then attempting to render the template.

Using the following test string:

```
<div>
  <h1>Hello World</h1>
  
  <h2>Okay</h2>
</div>
```

Throws the following exception:

```
Error: Parse error: <div> (1:6)
    at new cljs$core$ExceptionInfo (http://localhost:8080/client/cljs-runtime/cljs.core.js:36934:10)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (http://localhost:8080/client/cljs-runtime/cljs.core.js:36995:9)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (http://localhost:8080/client/cljs-runtime/cljs.core.js:36991:26)
    at Object.wet$impl$parser$parse_and_transform [as parse_and_transform] (http://localhost:8080/client/cljs-runtime/wet.impl.parser.js:423:25)
    at Function.wet.core.parse.cljs$core$IFn$_invoke$arity$2 (http://localhost:8080/client/cljs-runtime/wet.core.js:35:32)
    at Function.wet.core.parse.cljs$core$IFn$_invoke$arity$1 (http://localhost:8080/client/cljs-runtime/wet.core.js:31:23)
```

The Clojure version of that exception looks like:

```
(defn parse-and-transform
  [template]
  (let [parsed-template (parse template)]
    (cond
      (insta/failure? parsed-template)
      (let [{:keys [text line column]} parsed-template
            error-message (str "Parse error: " text " (" line ":" column ")")
            error-context {:type :wet/parse-error
                           :wet.error/line line
                           :wet.error/column column
                           :wet.error/text text}]
        (throw (ex-info error-message error-context)))
      :else (transform parsed-template))))
```

Where the exception is at the `throw`.

I can "fix" this by removing the new line characters in either the source file or code. I verified I'm using the unix `\n` character for newlines, not sure what would happen on Windows.

Thanks, let me know if I can provide more information.

**Comment by tdreyno** [comment]
Confirmed, via the REPL, that this works fine when using the library from CLJ, but CLJS fails.
